apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tennis-reg-tls-cert
  namespace: default
spec:
  secretName: tennis-reg-tls-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: #the name of the site
  dnsNames:
  - ## the name of the site
