name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'            
      - '**/.github/workflows/**'  
      - '**/docs/**'              
      - '**/*.md'                  
  workflow_dispatch:

env:
  GCP_KEY_PATH: /tmp/gcp-key.json
  KUBECONFIG_PATH: ~/.kube/config
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tennis-tournament-bun:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tennis-tournament-bun:latest

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 -d > $GCP_KEY_PATH

      - name: Authenticate to Google Cloud
        run: |
          gcloud auth activate-service-account --key-file $GCP_KEY_PATH
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Terraform
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

  deploy_app:
    runs-on: ubuntu-latest
    needs: [docker_build, terraform]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 -d > $GCP_KEY_PATH
          gcloud auth activate-service-account --key-file $GCP_KEY_PATH
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set compute/region ${{ secrets.GCP_REGION }}
          gcloud services enable cloudresourcemanager.googleapis.com

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            apt-transport-https ca-certificates gnupg \
            google-cloud-sdk kubectl google-cloud-sdk-gke-gcloud-auth-plugin

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $KUBECONFIG_PATH
          echo "KUBECONFIG=$KUBECONFIG_PATH" >> $GITHUB_ENV

      - name: Deploy to Kubernetes
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }} --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl apply -f mysql-deployment.yaml
          kubectl apply -f deployment.yaml
          kubectl get services
